--- LSP CompletionItemKind / SymbolKind -> palette key.
--- Shared by blink.cmp, dropbar and anything else that shows kinds, so the same
--- symbol has the same color everywhere.
return {
  Text = "muted",
  Method = "blue",
  Function = "blue",
  Constructor = "yellow",
  Field = "azure",
  Variable = "cyan",
  Class = "yellow",
  Interface = "yellow",
  Module = "purple",
  Property = "azure",
  Unit = "orange",
  Value = "orange",
  Enum = "orange",
  Keyword = "purple",
  Snippet = "green",
  Color = "red",
  File = "fg",
  Reference = "red",
  Folder = "blue",
  EnumMember = "orange",
  Constant = "orange",
  Struct = "yellow",
  Event = "red",
  Operator = "fg",
  TypeParameter = "orange",
  -- SymbolKind extras
  Namespace = "purple",
  Package = "purple",
  String = "green",
  Number = "orange",
  Boolean = "orange",
  Array = "orange",
  Object = "yellow",
  Key = "azure",
  Null = "muted",
  -- Sources
  Copilot = "cyan",
  Codeium = "cyan",
  Supermaven = "cyan",
}
